# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(choices=[('', ''), ('ABSA', 'ABSA'), ('Bidvest', 'Bidvest'), ('Capitec', 'Capitec'), ('FNB', 'FNB'), ('Investec', 'Investec'), ('Nedbank', 'Nedbank'), ('Standard', 'Standard'), ('Other', 'Other')], default='', max_length=30)),
                ('accno', models.DecimalField(decimal_places=0, max_digits=15)),
                ('branch', models.DecimalField(decimal_places=0, max_digits=6)),
                ('startDate', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('DOB', models.DateField(max_length=30)),
                ('UW', models.BooleanField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Policyholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('DOB', models.DateField(max_length=30)),
                ('relation', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father')], default='Mother', max_length=20)),
                ('cell', models.CharField(default='0', max_length=30)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='policyholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WME.Policyholder'),
        ),
        migrations.AddField(
            model_name='bank',
            name='policyholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WME.Policyholder'),
        ),
    ]
