# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='accept',
            field=models.BooleanField(default=False, max_length=3),
        ),
    ]
